package com.braffa.sellem.dao.utility.hsqldb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import org.apache.log4j.Logger;


public enum CopyOfCreateDatabase {
	instance;
	
	private static final Logger logger = Logger
			.getLogger(CopyOfCreateDatabase.class);

	public void setUpLogin() throws Exception {
		if (logger.isDebugEnabled()) {
			logger.debug("setUpLogin");
		}

		Class.forName("org.hsqldb.jdbc.JDBCDriver");
		Connection connection = DriverManager.getConnection("jdbc:hsqldb:"
				+ "sellMyThings", "braffa", "lindsay23");
		PreparedStatement ps;
		try {
			ps = connection.prepareStatement("drop TABLE LOGIN");
			ps.executeUpdate();
		} catch (Exception e) {

		}
		StringBuffer sql = new StringBuffer(
				"CREATE TABLE LOGIN ("
						+ " id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, "
						+ " userId VARCHAR(20), "
						+ " password VARCHAR(12), "
						+ " authorityLevel INTEGER, CRDATE TIMESTAMP, UPDDATE TIMESTAMP, PRIMARY KEY (userId) )");

		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer("SET TABLE LOGIN TYPE CACHED");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO LOGIN (userId, password, authorityLevel, CRDATE, UPDDATE)");
		sql.append(" VALUES ('Braffa', 'amanda33', 99,  CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP)");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO LOGIN (userId, password, authorityLevel, CRDATE, UPDDATE) ");
		sql.append(" VALUES ('georgie', 'georgie', 01,  CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP)");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO LOGIN (userId, password, authorityLevel, CRDATE, UPDDATE) ");
		sql.append(" VALUES ('admin', 'root', 99,  CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP)");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO LOGIN (userId, password, authorityLevel, CRDATE, UPDDATE) ");
		sql.append(" VALUES ('999999', '999999', 99,  CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP)");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();
		ps.close();
		connection.close();
	}

	public void setUpCatalog() throws Exception {
		Class.forName("org.hsqldb.jdbc.JDBCDriver");
		Connection connection = DriverManager.getConnection("jdbc:hsqldb:"
				+ "sellMyThings", "braffa", "lindsay23");
		PreparedStatement ps;
		try {
			ps = connection.prepareStatement("drop TABLE CATALOG");
			ps.executeUpdate();
		} catch (Exception e) {

		}
		StringBuffer sql = new StringBuffer("CREATE TABLE CATALOG ");
		sql.append(" (id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, ");
		sql.append(" author VARCHAR(50),         ");
		sql.append(" imageURL VARCHAR(255),      ");
		sql.append(" imageLargeURL VARCHAR(255), ");
		sql.append(" manufacturer VARCHAR(50),   ");
		sql.append(" productgroup VARCHAR(20),   ");
		sql.append(" productid VARCHAR(20),      ");
		sql.append(" productidtype VARCHAR(20),  ");
		sql.append(" source VARCHAR(20),         ");
		sql.append(" sourceid VARCHAR(20),       ");
		sql.append(" title VARCHAR(100),         ");
		sql.append(" CRDATE TIMESTAMP,           ");
		sql.append(" UPDDATE TIMESTAMP,          ");
		sql.append(" PRIMARY KEY ( productid ))  ");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer("SET TABLE CATALOG TYPE CACHED");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO CATALOG (author, imageURL, imageLargeURL, manufacturer, productgroup, "
						+ "productid, productidtype, source, sourceid, title, CRDATE, UPDDATE) VALUES (");
		sql.append("'Sandercoe Justin', ");
		sql.append("'http://ecx.images-amazon.com/images/I/41hdqEVaWML._SL75_.jpg', ");
		sql.append("'', ");
		sql.append("'Music Sales', ");
		sql.append("'Book', ");
		sql.append("'9781849386685', ");
		sql.append("'EAN', ");
		sql.append("'Amazon', ");
		sql.append("'1849386684', ");
		sql.append("'Justinguitar.Com Beginners Songbook J. Sandercoe (Easy Guitar With Notes and Tab)', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO CATALOG (author, imageURL, imageLargeURL, manufacturer, productgroup, "
						+ "productid, productidtype, source, sourceid, title, CRDATE, UPDDATE ) VALUES (");
		sql.append("'', ");
		sql.append("'http://ecx.images-amazon.com/images/I/511R3AC2C8L._SL75_.jpg', ");
		sql.append("'', ");
		sql.append("'Universal Pictures UK', ");
		sql.append("'DVD', ");
		sql.append("'5050582388237', ");
		sql.append("'EAN', ");
		sql.append("'Amazon', ");
		sql.append("'B000BKTBVI', ");
		sql.append("'Green Street (Hooligans) [DVD]', ");
		sql.append("CURRENT_TIMESTAMP, CURRENT_TIMESTAMP");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO CATALOG (author, imageURL, imageLargeURL, manufacturer, productgroup, "
						+ "productid, productidtype, source, sourceid, title, CRDATE, UPDDATE ) VALUES (");
		sql.append("'Craig Sharkie', ");
		sql.append("'http://ecx.images-amazon.com/images/I/412Ddd%2Bq1ZL._SL75_.jpg', ");
		sql.append("'', ");
		sql.append("'SITEPOINT (ACADEMIC)', ");
		sql.append("'Book', ");
		sql.append("'978098056856', ");
		sql.append("'EAN', ");
		sql.append("'Amazon', ");
		sql.append("'980576857', ");
		sql.append("'jQuery: Novice to Ninja', ");
		sql.append("CURRENT_TIMESTAMP, CURRENT_TIMESTAMP");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO CATALOG (author, imageURL, imageLargeURL, manufacturer, productgroup, "
						+ "productid, productidtype, source, sourceid, title, CRDATE, UPDDATE ) VALUES (");
		sql.append("'Subrahmanyam Allamaraju', ");
		sql.append("'http://ecx.images-amazon.com/images/I/51YKR0ZVKRL._SL75_.jpg', ");
		sql.append("'', ");
		sql.append("'WROX Press Ltd', ");
		sql.append("'Book', ");
		sql.append("'9781861005618', ");
		sql.append("'EAN', ");
		sql.append("'Amazon', ");
		sql.append("'186100561X', ");
		sql.append("'Professional Java Servlets 2.3 (Programmer to Programmer)', ");
		sql.append("CURRENT_TIMESTAMP, CURRENT_TIMESTAMP");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO CATALOG (author, imageURL, imageLargeURL, manufacturer, productgroup, "
						+ "productid, productidtype, source, sourceid, title, CRDATE, UPDDATE ) VALUES (");
		sql.append("'Mark Wutka', ");
		sql.append("'http://ecx.images-amazon.com/images/I/51TW6S55A4L._SL75_.jpg', ");
		sql.append("'', ");
		sql.append("'QUE', ");
		sql.append("'Book', ");
		sql.append("'9780789724410', ");
		sql.append("'EAN', ");
		sql.append("'Amazon', ");
		sql.append("'789724413', ");
		sql.append("'Using Java Server Pages and Servlets Special Edition (Special Edition Using)', ");
		sql.append("CURRENT_TIMESTAMP, CURRENT_TIMESTAMP");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		ps.close();
		connection.close();
	}

	public void setUpRegister() throws Exception {
		Class.forName("org.hsqldb.jdbc.JDBCDriver");
		Connection connection = DriverManager.getConnection("jdbc:hsqldb:"
				+ "sellMyThings", "braffa", "lindsay23");
		PreparedStatement ps;
		try {
			ps = connection.prepareStatement("drop TABLE REGISTER");
			ps.executeUpdate();
		} catch (Exception e) {

		}
		StringBuffer sql = new StringBuffer("CREATE TABLE REGISTER ");
		sql.append("(id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, ");
		sql.append(" userId  VARCHAR(20), ");
		sql.append(" email VARCHAR(50),     ");
		sql.append(" firstname VARCHAR(50), ");
		sql.append(" lastname VARCHAR(50),  ");
		sql.append(" telephone VARCHAR(50), ");
		sql.append(" CRDATE TIMESTAMP,      ");
		sql.append(" UPDDATE TIMESTAMP,     ");
		sql.append(" PRIMARY KEY ( id ))    ");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer("SET TABLE REGISTER TYPE CACHED");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO REGISTER (userId, email, firstname, lastname, telephone, CRDATE, UPDDATE) VALUES (");
		sql.append("'Braffa', ");
		sql.append("'dave.rogers@yahoo.co.uk', ");
		sql.append("'Dave',   ");
		sql.append("'Rogers', ");
		sql.append("'01388 445566',    ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO REGISTER (userId, email, firstname, lastname, telephone, CRDATE, UPDDATE) VALUES (");
		sql.append("'georgie', ");
		sql.append("'george.smith@yahoo.co.uk', ");
		sql.append("'george', ");
		sql.append("'smith', ");
		sql.append("'01642 641834', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO REGISTER (userId, email, firstname, lastname, telephone, CRDATE, UPDDATE) VALUES (");
		sql.append("'admin', ");
		sql.append("'andrew.jones@yahoo.co.uk', ");
		sql.append("'andrew', ");
		sql.append("'jones', ");
		sql.append("'01642 356745', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO REGISTER (userId, email, firstname, lastname, telephone, CRDATE, UPDDATE) VALUES (");
		sql.append("'SUE123', ");
		sql.append("'susan.smurf@yahoo.co.uk', ");
		sql.append("'susan', ");
		sql.append("'smurf', ");
		sql.append("'01388 731258', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();
		ps.close();
		connection.close();
	}

	public void setUpUserToCatalog() throws Exception {
		Class.forName("org.hsqldb.jdbc.JDBCDriver");
		Connection connection = DriverManager.getConnection("jdbc:hsqldb:"
				+ "sellMyThings", "braffa", "lindsay23");
		PreparedStatement ps;
		try {
			ps = connection.prepareStatement("drop TABLE USER_TO_CATALOG");
			ps.executeUpdate();
		} catch (Exception e) {

		}
		StringBuffer sql = new StringBuffer("CREATE TABLE USER_TO_CATALOG ");
		sql.append(" (id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, ");
		sql.append(" userId VARCHAR(20), " + " productId VARCHAR(20), ");
		sql.append(" productIndex VARCHAR(20), ");
		sql.append(" CRDATE TIMESTAMP,      ");
		sql.append(" UPDDATE TIMESTAMP,     ");		
		sql.append(" PRIMARY KEY ( id ))");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer("SET TABLE USER_TO_CATALOG TYPE CACHED");
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO USER_TO_CATALOG (userId, productId, productIndex, CRDATE, UPDDATE) VALUES (");
		sql.append("'georgie', ");
		sql.append("'9781861005618', ");
		sql.append("'2', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO USER_TO_CATALOG (userId, productId, productIndex, CRDATE, UPDDATE) VALUES (");
		sql.append("'georgie', ");
		sql.append("'9780789724410', ");
		sql.append("'2', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO USER_TO_CATALOG (userId, productId, productIndex, CRDATE, UPDDATE) VALUES (");
		sql.append("'Braffa', ");
		sql.append("'9780789724410', ");
		sql.append("'1', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();
		
		sql = new StringBuffer(
				"INSERT INTO USER_TO_CATALOG (userId, productId, productIndex, CRDATE, UPDDATE) VALUES (");
		sql.append("'Braffa', ");
		sql.append("'9781861005618', ");
		sql.append("'1', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();
		
		sql = new StringBuffer(
				"INSERT INTO USER_TO_CATALOG (userId, productId, productIndex, CRDATE, UPDDATE) VALUES (");
		sql.append("'Braffa', ");
		sql.append("'978098056856', ");
		sql.append("'1', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();

		sql = new StringBuffer(
				"INSERT INTO USER_TO_CATALOG (userId, productId, productIndex, CRDATE, UPDDATE) VALUES (");
		sql.append("'Braffa', ");
		sql.append("'5050582388237', ");
		sql.append("'1', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();
		
		sql = new StringBuffer(
				"INSERT INTO USER_TO_CATALOG (userId, productId, productIndex, CRDATE, UPDDATE) VALUES (");
		sql.append("'Braffa', ");
		sql.append("'9781849386685', ");
		sql.append("'1', ");
		sql.append("CURRENT_TIMESTAMP, ");
		sql.append("CURRENT_TIMESTAMP ");
		sql.append(")");
		System.out.println(sql.toString());
		ps = connection.prepareStatement(sql.toString());
		ps.executeUpdate();
		ps.close();
		connection.close();
	}

}
